### ISSUE TITLE
monterey b4 blackscreen after -v codes finished with only pointer responding

### ISSUE THREAD

**Issue by MotorBottle** [osy86/Polaris22Fixup#14]
IDK if it has something to do with the kext in this issue. My device is beelinks’s turbo g7 with 8709g. The device works properly at Big Sur 11.2 so I tried to install Monterey b4. I used to successfully install monterey on another laptop(uhd630) but this time it fails after all procedures finished. I can open the install disk, the installation goes well, but after the last reboot and the progress bar runs full, it turns out black screen and only the mouse pointer can move.

**Comment by keatliang2005** [comment]
try Whatevergreen version 1.5.1

suspect similar issue to 
https://github.com/osy/HaC-Mini/issues/614

**Comment by MotorBottle** [comment]
Somehow it shows nothing after finished running those codes, not showing the pointer anymore, no matter using WEG 151 or 152

**Comment by MotorBottle** [comment]
It turns to no signal output now, I don’t event remember how I let the pointer show up. But every time the process bar goes to closely half way (-v codes finished running), and then black out

**Comment by MotorBottle** [comment]
> try Whatevergreen version 1.5.1
> 
> suspect similar issue to
> [osy/HaC-Mini#614](https://github.com/osy/HaC-Mini/issues/614)

Does it have anything to do with opencore version? I’m still using 0.6.9 right now. But usually  it shouldn’t be affecting this. I guess it’s more of a graphic driver failure. May I try your efi setup? Maybe that can help locate some problems or mistakes. Much appreciated!

**Comment by keatliang2005** [comment]
i think the Polaris22Fixup not support macOS Monterey yet. something about the driver changed. this need to wait @osy86 to update while is final released

**Comment by keatliang2005** [comment]
maybe u can try to use this fork, no acceleration yet but it got visual
https://github.com/osy/Polaris22Fixup/issues/15

**Comment by MotorBottle** [comment]
> maybe u can try to use this fork, no acceleration yet but it got visual
> #15

Thanks for help!

**Comment by MotorBottle** [comment]
Switching to WEG 1.5.1 and the new polaris22fixup.kext here #16  fixes ths issue so I'll close this.
