### ISSUE TITLE
About Monterey 12.3 beta2

### ISSUE THREAD

**Issue by jisuye** [osy86/Polaris22Fixup#17]
The of this patch has failed. What shall I do?
![image](https://user-images.githubusercontent.com/31565431/153834663-dcf565af-f461-40c3-87c8-e7c379874c86.png)

**Comment by jisuye** [comment]
@goodbest can you help me ?

**Comment by sdyxxjj123** [comment]
I also had this problem after I updated to 12.3.

**Comment by osy** [comment]
Fixed in b0b9fbee3955be7a0e5c994ce05e1ce0b81dfbd0
