### ISSUE TITLE
Add support for macOS 13, Ventura - Blackscreen

### ISSUE THREAD

**Issue by sXmpwn** [osy86/Polaris22Fixup#18]
(NUC8i7HVK, Vega M GH)

The Kernel-Extension seems to be not working with the first Developer Beta of macOS Ventura and needs to be updated.

I was successful to install Ventura on the Hades Canyon with a pre-Alpha OpenCore 0.8.2 build and `AvoidRuntimeDefrag` enabled but I discovered that it initially went to a black screen after `IOConsoleUsers` (last line of verbose, related to graphics).
After disabling the Kext and GpuSpoof I could boot at least without graphics acceleration (meaning VESA, 7 MB VRAM).

I'm up for everything if you need a tester.

**Comment by osy** [comment]
Fixed in bfe992e6b86a3c0d4c039701b86de9fb94ae5d1c
