### ISSUE TITLE
This kext need update for ventura 13.3，something went wrong

### ISSUE THREAD

**Issue by 13months** [osy86/Polaris22Fixup#19]

**Comment by 13months** [comment]
my nuc update to ventura 13.3
display went wrong like this
pls help me,thanks very much.

<img width="788" alt="花屏-2" src="https://user-images.githubusercontent.com/19258580/228209997-8cbe2380-ce0e-49de-b683-6bc08cccf53c.png">
<img width="756" alt="花屏-1" src="https://user-images.githubusercontent.com/19258580/228210041-9842b8de-1398-4271-8602-3f108d881862.png">
<img width="1812" alt="花屏-3" src="https://user-images.githubusercontent.com/19258580/228210085-617c7935-4b85-4205-845f-03d729f8235b.png">

**Comment by Purpleman666** [comment]
I got exactly the same issue. Is there anyway to fix this ? Thanks

**Comment by Purpleman666** [comment]
Awsome, it works well. Thank you so much.
