### ISSUE TITLE
Sonoma blackscreen (Potential Fix)

### ISSUE THREAD

**Issue by Nulled-Out** [osy86/Polaris22Fixup#22]
**Edit**: I was able to get it to boot in safe-mode once with no wallpaper or acceleration but normal mode just says "Check device power" on my monitor or is blank 
 
Not sure if it's this or something else but it seems to be an issue for the NUC8I7HVK with PolarisFixUp 🤔

**Comment by Baio1977** [comment]
https://github.com/Lorys89/Polaris22Fixup
Test this

**Comment by Nulled-Out** [comment]
> https://github.com/Lorys89/Polaris22Fixup Test this

No release/kext file, how do I use it from the source?

**Comment by Baio1977** [comment]
[Polaris22Fixup.kext.zip](https://github.com/osy/Polaris22Fixup/files/13515171/Polaris22Fixup.kext.zip)
 Update Sonoma

**Comment by Malumen** [comment]
> [Polaris22Fixup.kext.zip](https://github.com/osy/Polaris22Fixup/files/13515171/Polaris22Fixup.kext.zip) Update Sonoma

Can we use this on Ventura as well?

**Comment by Baio1977** [comment]
https://github.com/Lorys89/Polaris22Fixup/actions/runs/9534527078
This Kext work on 10.14+ .
Bugs on Sequoia, if possible they will be fixed when the release version of the OS comes out.
