### ISSUE TITLE
Graphical glitches present on Sequoia Beta 1

### ISSUE THREAD

**Issue by Baio1977** [osy86/Polaris22Fixup#23]
I compiled the kext with Sequoia support with the new Lilu 1.6.8 but I notice graphic bugs already present in previous versions of Apple OS.
If you can solve it it would be TOP.
[Polaris22Fixup.kext.zip](https://github.com/user-attachments/files/15856505/Polaris22Fixup.kext.zip)

https://github.com/Lorys89/Polaris22Fixup

Bug Images
![photo_2024-06-16_08-43-05 (3)](https://github.com/osy/Polaris22Fixup/assets/59058746/cf280203-4a22-47dd-914d-4df512ad8c9a)
![photo_2024-06-16_08-43-05 (2)](https://github.com/osy/Polaris22Fixup/assets/59058746/f9313a0d-c62c-43f2-a0a4-391af6cdf803)
![photo_2024-06-16_08-43-05](https://github.com/osy/Polaris22Fixup/assets/59058746/3e57a58a-8c4f-4a36-bb81-f29ed9a1805f)

**Comment by goodbest** [comment]
Well, it's still the same old thing.

We have to find the binary patch in the kernel, and hoping the existing patch to be alive in newer updates.
Just like the following lines. 
https://github.com/osy/Polaris22Fixup/blob/8d09f8f544283c3c4fd12ed0c6cf37c73cdfde4e/Polaris22Fixup/kern_start.cpp#L195

In fact, the binary patch is not hard to find, but is always changing during betas and updates.
How about waiting for a while? Sequoia (including Sonoma) does not introduce any must-have features  to me.

**Comment by Baio1977** [comment]
For Sonoma ALL Version this Kext is good https://github.com/Baio1977/NUC8i7HVK-Hackintosh/tree/main/OC%201.0.0/EFI/OC/Kexts/Polaris22Fixup.kext/Contents.

**Comment by Lorys89** [comment]
KDK does not ship AMDMTLBronzeDriver.bundle, Where can we find the binary? 
That of s/l/e It's no good.

**Comment by goodbest** [comment]
@Baio1977 @Lorys89

Can you test this kext I build? The glitches is fixed for Sequoia.
[Polaris22Fixup.kext.zip](https://github.com/user-attachments/files/16484351/Polaris22Fixup.kext.zip)

Of course the latest nightly build Lilu is needed.
https://github.com/dortania/build-repo/releases/download/Lilu-4256f43/Lilu-1.6.8-RELEASE.zip
