### ISSUE TITLE
Incompatible with Lilu user patches

### ISSUE THREAD

**Issue by osy** [osy86/Polaris22Fixup#3]
Because we hook `cs_validate_range` as well as Lilu (when user patches are used), this would cause issues including the order of the hooks and when one plugin decides to remove the hooks.

An ideal solution would be to detect if Lilu is available, make sure to always load after Lilu, and then patch using Lilu when detected.

**Comment by osy** [comment]
Lilu has been updated to support multiple hooks on a function. We should be compatible with Lilu again if we make use of it.

https://github.com/acidanthera/bugtracker/issues/390

**Comment by osy** [comment]
Reopening to support new Lilu api which would remove dependency on load order.

**Comment by osy** [comment]
Since Lilu was updated to support multiple patches and since we are moving to OC, VirtualSMC, and already depend on AppleALC, the arguments to not depend on Lilu no longer has much weight. The next release will simplify the codebase and re-introduce Lilu as a dependency.

**Comment by vit9696** [comment]
@osy86 perhaps it is reasonable to merge this kext into WhateverGreen? It is not the first time for us to have userspace patches for GPU support there as we already have Shiki and CDF code there.

**Comment by osy** [comment]
The patch doesn’t apply to anything other than VegaM so I don’t want to pollute WG codebase with the hacky way that I’m patching user code. Maybe it would make more sense if the patch applies for any other cards.

**Comment by vit9696** [comment]
Right, this makes sense to me.
