### ISSUE TITLE
new build not working on 10.14.6 18G84

### ISSUE THREAD

**Issue by XploitKR** [osy86/Polaris22Fixup#4]
is this lilu.kext update need or 10.15 only work?

**Comment by osy** [comment]
Are you using Lilu 1.3.8?

**Comment by XploitKR** [comment]
built-in HaC-Mini.

**Comment by osy** [comment]
That's not up to date. As you may have noticed the latest version is not included in HaC mini yet. It will be soon after some more changes.

**Comment by XploitKR** [comment]
ok. wait for new release.
i want working on 10.15 catalina.
