### ISSUE TITLE
vfio possible?

### ISSUE THREAD

**Issue by gotschi** [osy86/Polaris22Fixup#5]
I'm running macos via kvm on a hades canyon 8i7hvk
with the VegaM passed through to Osx via vfio,
I can fake the PID and inject ATI and get the Card to display
But I can't get the card to display with just the simple

`4GcAAA==`
patch...

I try to apply it to PciRoot(0x0)\Pci(0x2,0x0)\Pci(0x0,0x0)
which is the PCID of the Card inside the VM but I can't get it to work.
Also Polaris is the issue I really have, since Faking the ID and injecting ATI seems to work
(with no audio atm, also don't really know why...)

please see my bootlog here:
https://paste.ubuntu.com/p/pT6wR5HK6C/

and the bootlog without injection:
https://paste.ubuntu.com/p/WJHfTjc68Y/

I hope you can give me some insight to this

edit: I got the video patch working now but polaris doesn't seem to get patched, I still see artefacts
edit2: hdmi with audio works fine, had the wrong pci bus set for vfio

everything runs fine, except for the polarisfix :/

**Comment by osy** [comment]
Try the new version that uses Lilu.
