### ISSUE TITLE
Kext compiled with with Xcode 11.4 causes immediate kernel panic

### ISSUE THREAD

**Issue by ghost** [osy86/Polaris22Fixup#6]
Following Xcode update to 11.4 the kext compiles fine but produces an immediate kernel panic on Catalina 10.15.4 running on a NUC8i7HNK. Here is the report:
`panic(cpu 6 caller 0xffffff8010a4c32a): Kernel trap at 0xffffff7f95c79759, type 13=general protection, registers:
CR0: 0x000000008001003b, CR2: 0xffffff83ae7c6000, CR3: 0x00000001e22a0001, CR4: 0x00000000003626e0
RAX: 0x00e3a791903d00e6, RBX: 0xffffff8050753d00, RCX: 0xffffff80507c2000, RDX: 0x0000000000000000
RSP: 0xffffff83c201b148, RBP: 0xffffff83c201b5d0, RSI: 0x0000000000000000, RDI: 0xffffff8050753d00
R8:  0x0000000000001000, R9:  0xffffff83c201b720, R10: 0x0000000000000480, R11: 0xffffff804b155000
R12: 0xffffff80507c2000, R13: 0x0000000000000000, R14: 0xffffff80507c1360, R15: 0x0000000000001000
RFL: 0x0000000000010286, RIP: 0xffffff7f95c79759, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff83ae7c6000, Error code: 0x0000000000000000, Fault CPU: 0x6, PL: 0, VF: 0

Backtrace (CPU 6), Frame : Return Address
0xffffff8010754220 : 0xffffff80109215cd mach_kernel : _handle_debugger_trap + 0x49d
0xffffff8010754270 : 0xffffff8010a5a3c5 mach_kernel : _kdp_i386_trap + 0x155
0xffffff80107542b0 : 0xffffff8010a4bf7e mach_kernel : _kernel_trap + 0x4ee
0xffffff8010754300 : 0xffffff80108c7a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8010754320 : 0xffffff8010920c97 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff8010754420 : 0xffffff8010921087 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff8010754470 : 0xffffff80110c2c7c mach_kernel : _panic + 0x54
0xffffff80107544e0 : 0xffffff8010a4c32a mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff8010754660 : 0xffffff8010a4c028 mach_kernel : _kernel_trap + 0x598
0xffffff80107546b0 : 0xffffff80108c7a40 mach_kernel : _return_from_trap + 0xe0
0xffffff80107546d0 : 0xffffff7f95c79759 com.osy86.Polaris22MetalFixup : __ZL17gTrampolineToOrig
0xffffff83c201b5d0 : 0xffffff8010ef77f7 mach_kernel : _load_machfile + 0x1ae7
0xffffff83c201b900 : 0xffffff8010ef5fb9 mach_kernel : _load_machfile + 0x2a9
0xffffff83c201b9c0 : 0xffffff8010e60e03 mach_kernel : _kctl_fill_socketinfo + 0xd03
0xffffff83c201bd70 : 0xffffff8010e68c4e mach_kernel : _posix_spawn + 0x3efe
0xffffff83c201bdf0 : 0xffffff8010e69de2 mach_kernel : ___mac_execve + 0x372
0xffffff83c201be90 : 0xffffff8010e6a37b mach_kernel : _load_init_program + 0x1db
0xffffff83c201bf00 : 0xffffff8010e2f10d mach_kernel : _bsdinit_task + 0x6d
0xffffff83c201bf20 : 0xffffff8010918f29 mach_kernel : _ast_taken_user + 0x119
0xffffff83c201bf60 : 0xffffff80108c7a0c mach_kernel : _return_from_trap + 0xac
      Kernel Extensions in backtrace:
         com.osy86.Polaris22MetalFixup(1.0)[0E6AF29A-E5AA-39F2-97C8-17BAB86085D9]@0xffffff7f95c78000->0xffffff7f95c7ffff

BSD process name corresponding to current thread: init
Boot args: mbasd=1 alcid=11 shikigva=80 keepsyms=1

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x0000000010600000
Kernel text base: 0xffffff8010800000
__HIB  text base: 0xffffff8010700000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: NO (0xe00002d8)

System uptime in nanoseconds: 825855433`

Happy to help with testing etc.

**Comment by osy** [comment]
As you may have already discovered, Xcode 11.4 is not supported. I keep an installation of 10.3 for this reason.
